### ISSUE TITLE
Can this be registered?

### ISSUE THREAD

**Issue by chkwon** [matago/TSPLIB.jl#4]
Thanks for a very cool package.  Can this be registered? I'd like to develop some packages that depend on TSPLIB.jl. Registering this package will greatly be helpful!

**Comment by matago** [comment]
Hey @chkwon .  Thank you for your interest in this library.  I have not actively used this library since developing it during grad school.  I am open to reviewing any improvements you deem to be appropriate.  If you are interested in actively developing and continuing to use this library would you want to be added as a maintainer?

**Comment by matago** [comment]
All set.  Welcome aboard!

**Comment by chkwon** [comment]
@matago Can you install [this JuliaRegistrator app](https://github.com/apps/juliateam-registrator/installations/new) in this repository?

**Comment by matago** [comment]
Should be installed now.

**Comment by chkwon** [comment]
Awesome! Thanks!
